---

- name: Install desired snap packages
  community.general.snap:
    name:
      - firefox
      - chromium
      - cups

- name: Enable firefox to print
  ansible.builtin.command:
    cmd: 'snap connect firefox:cups-control'
  changed_when: true
